project:
  type: website
  render:
    - "./*.qmd"
    # - "resources/*.qmd"
    # - "slides/*.qmd"
    - "exercises/*.qmd"
    # - "supplemental/*.qmd"
  output-dir: "docs"
  resources:
    - "include/snd/*.m4a"
    - "include/snd/*.wav"
    - "include/img/*.png"
    - "include/img/*.jpg"
    - "include/img/*.gif"
    - "include/img/*.mov"

website:
  title: "PSY 511.001"
  announcement:
    content: "Welcome to PSY 511.001! If you find a broken link or typo, I'll buy you a coffee."
    position: below-navbar
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - evaluation.qmd
      - policies.qmd
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring
  repo-actions: [edit, issue]
  page-footer:
    left: "Copyright © 2025- Rick Gilmore"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring
    background: light
    border: true
  page-navigation: true
  bread-crumbs: false
  reader-mode: false

bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]

csl: include/bib/apa.csl  
format:
  html:
    theme: [cosmo, include/css/psu.scss]
    toc: true
    toc-depth: 3
    fig-align: center
    fontsize: 1.1em
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    date: today
editor: source
    