project:
  type: website
  render:
    - "*.qmd"
    - "slides/*.qmd"
    - "exercises/*.qmd"
    - "resources/*.qmd"
  output-dir: "docs"
  execute-dir: project
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "PSY 511.001"
  announcement:
    content: "[Course evaluations](https://seeq-student.k8s.psu.edu/SEEQ) are live. Please take a moment and rate the course."
    position: below-navbar
    icon: info-circle
    dismissable: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - evaluation.qmd
      - policies.qmd
      - section: "Exercises"
        contents:
          - text: "Ex LVL • Levels/Terms"
            href: exercises/ex-LVL.qmd
          - text: "Ex ANAT • Anatomy"
            href: exercises/ex-ANAT.qmd
          - text: "Ex PA • Perception & Action"
            href: exercises/ex-PA.qmd
          - text: "Final Project proposal"
            href: exercises/final-project.qmd
          - text: "Measuring emotion"
            href: exercises/ex-EMO.qmd
          - text: "Ex ZZ • Sleep & Circadian Rhythms"
            href: exercises/ex-ZZ.qmd
          - text: "Ex EVO • Evolution"
            href: exercises/ex-EVO.qmd
          - text: "Ex DEV • Development"
            href: exercises/ex-DEV.qmd
          - text: "Ex PHYS • Neurophysiology I"
            href: exercises/ex-PHYS.qmd
          - text: "Ex AP • Neurophysiology II"
            href: exercises/ex-AP.qmd
          - text: "Ex CHEM • Neurochemistry"
            href: exercises/ex-CHEM.qmd
      - section: "Slides"
        contents:
          - text: "Wk 01 • Thu Jan 14"
            href: slides/wk-01-2026-01-15-intro.qmd
          - text: "Wk 02 • Thu Jan 21"
            href: slides/wk-02-2026-01-22-anatomy.qmd
          - text: "Wk 03 • Thu Jan 29"
            href: slides/wk-03-2026-01-29-action.qmd
          - text: "Wk 04 • Thu Feb 05"
            href: slides/wk-04-2026-02-05-perception.qmd
          - text: "Wk 05 • Thu Feb 12"
            href: slides/wk-05-2026-02-12-learning-memory.qmd
          - text: "Wk 06 • Thu Feb 19"
            href: slides/wk-06-2026-02-19-language.qmd
          - text: "Wk 07 • Thu Feb 26"
            href: slides/wk-07-2026-02-26-emotion.qmd
          - text: "Wk 08 • Thu Mar 5"
            href: slides/wk-08-2026-03-05-sleep.qmd
          - text: "Wk 09 • Thu Mar 19"
            href: slides/wk-09-2026-03-19-evo-devo.qmd
          - text: "Wk 10 • Thu Mar 26"
            href: slides/wk-10-2026-03-26-cells.qmd
          - text: "Wk 11 • Thu Apr 02"
            href: slides/wk-11-2026-04-02-neural-comm.qmd
          - text: "Wk 12 • Thu Apr 09"
            href: slides/wk-12-2026-04-09-neurochemistry.qmd
          - text: "Wk 13 • Thu Apr 16"
            href: slides/wk-13-2026-04-16-schizophrenia.qmd
          - text: "Wk 14 • Thu Apr 24"
            href: slides/wk-14-2026-04-24-aff-disorders.qmd
      - section: "Resources"
        contents:
          - text: "Student interests (Ex LVL)"
            href: resources/terms-concepts.qmd
          - text: "Essay tips"
            href: exercises/essay-tips.qmd
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © 2025 Rick Gilmore under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring/
    background: light
    border: true
  page-navigation: true
  bread-crumbs: false
  
format:
  html:
    theme: [cosmo, include/css/psu.scss]
    mainfont: roboto
    fontsize: 1.1em
    
    toc: true
    toc-depth: 4
    
    fig-align: center
  
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    
    date-modified: last-modified
    date: today
    
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib, include/bib/grateful-refs.bib]
    csl: include/bib/apa.csl
    
    html-math-method: mathjax
  revealjs:
    revealjs-plugins:
      - embedio
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]
    csl: include/bib/apa.csl

editor: source

knitr:
  opts_chunk:
    fig.path: include/fig/
    