project:
  type: website
  render:
    - "*.qmd"
    - "slides/*.qmd"
    - "!exercises/*.qmd"
    - "!resources/*.qmd"
  output-dir: "docs"

website:
  title: "PSY 511.001"
  announcement: 
    content: "Exercise [LVL](exercises/ex-LVL.qmd) is due Thursday." 
    position: below-navbar
    icon: info-circle
    dismissable: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - schedule.qmd
      - evaluation.qmd
      - policies.qmd
      - section: "Exercises"
        contents:
          - text: "Ex LVL • Levels/Terms"
            href: exercises/ex-LVL.qmd
          - text: "Ex ANAT • Anatomy"
            href: exercises/ex-ANAT.qmd
      - section: "Slides"
        contents:
          - text: "Wk 01 • Thu Jan 14"
            href: slides/wk-01-2026-01-15-intro.qmd
          - text: "Wk 02 • Thu Jan 21"
            href: slides/wk-02-2026-01-22-anatomy.qmd
  repo-url: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring
  repo-actions: [edit, issue]
  repo-subdir: src
  page-footer:
    left: "Copyright © 2025 Rick Gilmore under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)"
    center: "Built with [Quarto](https://quarto.org/)"
    right: 
      - icon: github
        href: https://github.com/psu-psychology/psy-511-scan-fdns-2026-spring/
    background: light
    border: true
  page-navigation: true
  bread-crumbs: false
  
format:
  html:
    theme: default
    css: include/css/styles.css
    toc: true
    toc-depth: 4
    fig-align: center
    fontsize: 1.1em
    number-sections: false
    citations-hover: true
    footnotes-hover: true
    date-modified: last-modified
    date: today
    bibliography: [include/bib/packages.bib, include/bib/psu-repro.bib, include/bib/psy-511.bib]
    csl: include/bib/apa.csl
    html-math-method: mathjax
  revealjs:
    revealjs-plugins:
      - embedio
editor: source
    