## January 12-16 {- #week-01}

### Thursday, January 15

#### Topics

- Structure of the course
- Levels of analysis
- Causality in brain and behavior
- Does neuroscience need behavior? What does psychology need?

#### Readings

- Required:
  - @Krakauer2017-xl
  - @Parada2018-rp
  - @Newcombe2017-wu
- Optional:
  - @Siddiqi2022-wl
  - @Churchland1988-aj
  - @Favela2020-uc
  - @Ross2024-nr
  
#### Materials

- [Slides](slides/wk01-2025-01-16.html)
- [Exercise 01](exercises/ex01.html) [assigned]{.green_assigned} | [PDF](exercises/ex01.pdf) |

## January 19-23 {- #week-02}

### Thursday, January 22

#### Topic(s)

- Action

#### Reading(s)

- @Shenoy2013-zi

#### Materials

- [Action notes](resources/action.qmd)


<!-- ### Wednesday, January 21 -->

<!-- - [Exercise 01](exercises/ex01.html) write-up [due]{.orange_due} | [Canvas dropbox]() | -->

<!-- ### Thursday, January 22 -->

<!-- #### Topics -->

<!-- - Neuroanatomy lab -->

<!-- #### Readings -->

<!-- - [Neuroanatomy notes](resources/anatomy.qmd) -->

<!-- #### Materials -->

<!-- - [Slides](slides/wk02-2025-01-23.qmd). [PDF](slides/wk02-2025-01-23.pdf) -->
<!-- - [Allen Brain Atlas](http://atlas.brain-map.org/atlas?atlas=138322605#atlas=138322605&structure=10390&resolution=119.78&x=31680.307112068967&y=42751.00179211847&zoom=-6&plate=112360949). -->
<!-- - [Exercise 02](exercises/ex02.html) [distributed]{.green_assigned} | [PDF](exercises/ex02.pdf) | -->

## January 26-30 {- #week-03}

### Thursday, January 29

#### Topic(s)

- Perception

#### Materials

- [Perception notes](resources/perception.qmd)

<!-- ### Wednesday, January 28 -->

<!-- - [Exercise 02](exercises/ex02.html) [due]{.orange_due} | [Canvas dropbox]() | -->

<!-- ### Thursday, January 29 -->

<!-- #### Topics -->

<!-- - Cellular neuroscience I -->
<!--   - Anatomy -->
<!--   - Physiology -->
<!--     - Resting potential -->

<!-- #### Readings -->

<!-- - [Cellular neuroscience notes](resources/cells.html) | [PDF](resources/cells.pdf) | -->
<!-- - Optional: -->
<!--   - @Zeng2017-sg -->
<!--   - @Oliveira2015-ky -->
<!--   - @Distefano-Gagne2023-gt -->

<!-- #### Materials -->

<!-- - [Slides](slides/wk03-2025-01-30.qmd) | [PDF](slides/wk03-2025-01-30.pdf) | -->
<!-- - [Exercise 03](exercises/ex03.html) [distributed]{.green_assigned}. | [PDF](exercises/ex03.pdf) | -->

## February 2-6 {- #week-04}

### Thursday, February 05

#### Topic(s)

- Learning & memory

<!-- ### Thursday, February 05 -->

<!-- #### Topics -->

<!-- - Cellular neuroscience II -->
<!--   - Action potential -->
<!--   - Synaptic transmission -->
<!-- - [Exercise 04](exercises/ex04.html) [assigned]{.green_assigned}. | [PDF](exercises/ex04.pdf) | -->

<!-- #### Readings -->

<!-- - [Cellular neuroscience notes](resources/cells.qmd) -->

<!-- #### Materials -->

<!-- - [Slides](slides/wk04-2025-02-06.qmd) -->

## February 9-13 {- #week-05}

### Thursday, February 12

#### Topic(s)

- Emotion

<!-- ### Wednesday, February 11 -->

<!-- - [Exercise 03](exercises/ex03.html) write-up [due]{.orange_due}. | [Canvas dropbox]() | -->

<!-- ### Thursday, February 12 -->

<!-- #### Topics -->

<!-- - Neurochemistry -->
<!--   - Neurotransmitters -->
<!--   - Hormones -->
<!-- - Neurocomputing -->

<!-- #### Readings -->

<!-- - [Neurochemistry notes](resources/neurochemistry.qmd) -->
<!-- - Optional: @Sarkar2016-qf. -->

<!-- #### Materials -->

<!-- - [Slides](slides/wk05-2025-02-13.qmd) -->
<!-- - [Exercise 05](exercises/ex05.html) [distributed]{.green_assigned} | [PDF](exercises/ex05.pdf) | -->

## February 16-20 {- #week-06}

<!-- ### Wednesday, February 25 -->

<!-- - [Exercise 05](exercises/ex05.html) [write-up due]{.orange_due} | [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17065114) | -->

### Thursday, February 19

#### Topic(s)

- Evolution of the nervous system

#### Readings

<!-- - [evolution resources](resources/evolution.qmd) -->
- Required:
  - @Charvet2012-bg
  - @hofman_evolution_2014
- Optional: 
  - @Castrillon2023-mt

#### Materials

- [Notes](resources/evolution.qmd)
- [Exercise 07](exercises/ex07.html) [distributed]{.green_assigned} | [PDF](exercises/ex07.pdf) |

<!-- ### Wednesday, February 18 -->

<!-- - [Exercise 04](exercises/ex04.html) write-up [due]{.orange_due} | [Canvas dropbox]() | -->

<!-- ### Thursday, February 19 -->

<!-- #### Topics -->

<!-- - Methods in neuroscience -->

<!-- #### Readings -->

<!-- - Watch: @Mitcbmm2019-oj -->
<!-- - Review: @noauthor_undated-wk -->
<!-- - Recommended: -->
<!--   - @Cohen2017-og -->
<!--   - @Hillman2014-xv -->
<!-- - Optional:  -->
<!--   - @Koch2022-wk -->

<!-- #### Materials -->

<!-- - [Methods notes](resources/methods.qmd) -->
<!-- - [Exercise 06](exercises/ex06.html) [distributed]{.green_assigned} | [PDF](exercises/ex06.pdf) | -->

## February 23-27 {- #week-07}

<!-- ### Wednesday, March 04 -->

<!-- - [Exercise 06](exercises/ex06.qmd) write-up [due]{.orange_due} | [Canvas dropbox]() | -->
<!-- - [Final project](exercises/final-project.qmd) proposal [due]{.orange_due} -->

### Thursday, February 26

#### Topic(s)

- Development of the nervous system

#### Readings

- Required:
  - @Cao2017-bl
  - @Blumberg2023-fs
- Optional:
  - @Larsen2023-wx
  - @Rakic2009-jk

#### Materials

- [Notes](resources/development.qmd)
- [Exercise 06](exercises/ex08.html) [distributed]{.green_assigned} | [PDF](exercises/ex08.pdf) |

## March 2-6 {- #week-08}


## March 9-13 *Spring Break* {- #spring-break}

## March 16-20 {- #week-09}

### Wednesday, March 18

- [Exercise 07](exercises/ex07.qmd) write-up [due]{.orange_due} | [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17090042) |

### Thursday, March 19

## March 23-27 {- #week-10}

### Wednesday, March 25

- [Exercise 08](exercises/ex08.qmd) write-up [due]{.orange_due} | [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17090083) |

### Thursday, March 26

#### Topics

- Perception & action

#### Readings

- @Khalsa2018-gf
- @Shenoy2013-zi

#### Materials

- [Perception notes](resources/perception.qmd)
- [Action notes](resources/action.qmd)

## March 33 - April 3 {- #week-11}

### Thursday, April 02

#### Topics

- Cognition & Language

#### Readings

- @Miller2001-qu
- @Tuckute2024-gv

#### Materials

- [Notes](resources/cognition-language.qmd)

## April 6-10 {- #week-12}

### Thursday, April 09

#### Topics

- Neuroscience of emotion

#### Readings

- @Malezieux2023-as
- @Watabe-Uchida2017-gi

#### Materials

- [Notes](resources/fear-stress-reward.qmd)

## April 13-17 {- #week-13}

### Thursday, April 16

#### Topics

- Disorder & disease I

#### Readings

- @Howes2023-vk
- @Volk2015-ki

#### Materials

- [Notes](resources/schizophrenia.qmd)

## April 20-24 {- #week-14}

### Thursday, April 23

#### Topics

- Disorder & disease II

#### Readings

- @Moncrieff2022-os
- @Namkung2017-gc

#### Materials

- [Notes](resources/affective-disorders.qmd)

## April 27 - May 1 {- #week-15}

### Thursday, April 30

#### Topics

- Student presentations
- Beethoven and the Cerebral Symphony

#### Materials

- [Slides](slides/wk15-2025-05-01.qmd)

## May 4-8 {- #finals-week}

### Thursday, May 07

- [Final Project](exercises/final-project.qmd) write-up [due]{.orange_due} | [Canvas dropbox](https://psu.instructure.com/courses/2379931/assignments/17170786)
