---
title: "Evaluation"
---

PSY 511 course performance will be evaluated based on the following scheme:

| Component           | Points                      | % of Grade |
|---------------------|------------------------------|-------|
| Exercises           | 10 pts/exercise * 6 = 60 pts | 50    |
| Final Project Proposal | 10                   | 8.3    |
| Final Paper/Project | 35                       | 29     |
| Bonus               | 15                           |  12.5    |   
| **TOTAL**           | **120**                      | **100** |
| Extra Credit        | One additional exercise may be submitted for up to 10 points | |

There are 11 exercises assigned throughout the semester. You are encouraged to do all of them. However, six (6) of these count toward the final grade. 

The final project proposal is worth 10 points, and the final project submission is worth 35 points.

One bonus point will be assigned for each class you attend and participate in actively. Note that if you submit more than 6 exercises, any points earned for these will count as bonus points, up to the 15 maximum.

::: {.callout-note}
## For clinical students

- Exercises LVL, ANAT, AP, ZZ, EVO, DEV, PHYS, and AP cover material related to biology-related discipline specific knowledge (DSK). 
- Exercises LVL, AP, and DEV cover material related to cognitive-related discipline specific knowledge (DSK).
- Exercises LVL, EMO, and DEV cover material related to affect-related discipline specific knowledge (DSK).
- Classroom participation and the final paper/project assess advanced integrative knowledge (AIK).
- For students to receive a passing grade (B or better for the course, they must receive a passing grade (B or better or Satisfactory) for each assignment or activity designed to assess DSK and IAK.
- Students have one opportunity to re-do an assignment if they do not initially receive a passing grade.
:::

### Grading Scheme

| Points  | Percent | Grade |
|---------|---------|-------|
| 113-120  | 94-99   | A     |
| 108-112   | 90-93   | A-    |
| 104-107   | 87-89   | B+    |
| 101-103   | 84-86   | B     |
| 96-100   | 80-83   | B-    |
| 92-95   | 77-79   | C+    |
| 84-91   | 70-76   | C     |
| 72-83   | 60-69   | D     |
| <72     | <60     | F     |

## Exercises

There will be eight (8) exercises throughout the term.
Six (6) of the 8 will count toward the final course grade.
Significant work on these can and will be done in-class.
More details will be provided for each exercise.

## Paper/Project

A significant part of the grade in PSY 511 is a [final paper or project](exercises/final-project.qmd).

The paper or project can take on a number of forms, depending on a student's scholarly interests.

A 1-2 page project proposal, worth ten (10) points, will be due before Spring Break.
The final project submission will be due during finals week.
