---
title: "Exercise DEV • Development"
subtitle: "**Name:**____________________________"
---

```{r}
#| echo: false
psy_511_vars <- readr::read_csv("../data/csv/psy-511-vars.csv", show_col_types = FALSE)
ex_due <- psy_511_vars |>
  dplyr::filter(name == "WK_10_DATE") |>
  dplyr::select(value) |>
  as.character()

canvas_db <- psy_511_vars |>
  dplyr::filter(name == "EX_DEV_CANVAS") |>
  dplyr::select(value) |>
  as.character()
```

## Goals

1. Practice taking a *developmental neuroscience* perspective to psychological phenomena.
2. Illustrate how taking such a perspective does or does not inform understanding about a particular phenomenon.

## Activity

1. Choose a psychological domain that interests you.
2. In the spirit of [@Blumberg2023-fs], write a short essay (3-5 pp) where you apply a developmental neuroscience perspective to the domain.  In doing so, concisely answer the following questions:
  - How does psychological functioning change over development?
  - What brain system(s) are most directly implicated in the phenomenon?
  - Does our current understanding of developmental patterns in these systems provide useful information about the domain?
  - What information about brain structure or function is needed to understand the phenomenon more thoroughly?

## Submission details

- Submit your write-up by **`{r} ex_due`** via the Canvas [dropbox](`{r} canvas_db`).
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.

