---
title: "Exercise EVO • Evolution"
subtitle: "**Name:**____________________________"
---

```{r}
#| echo: false
psy_511_vars <- readr::read_csv("data/csv/psy-511-vars.csv", show_col_types = FALSE)
ex_evo_due <- psy_511_vars |>
  dplyr::filter(name == "WK_10_DATE") |>
  dplyr::select(value) |>
  as.character()

canvas_db <- psy_511_vars |>
  dplyr::filter(name == "EX_EVO_CANVAS") |>
  dplyr::select(value) |>
  as.character()
```

## Goals

1. To practice thinking and reasoning critically about how evolutionary perspectives can inform understanding about psychological phenomena.

## Activity

::: {.callout-important}
## Revised
This exercise was revised on 2026-04-09.
:::

Write a short (3-5 pp) essay about how and why taking an evolutionary perspective on psychological phenomena can inform understanding. In doing so, you may wish to address some of the following points:

1. What feature(s) of the human brain are similar to closely related animals (e.g., mammals and especially primates)?
2. What feature(s) of the human brain distinguish it from these closely related animals?
3. Why is it especially hard to tie changes in human brain structure to particular human psychological characteristics?
4. Consider a psychological domain that interests you, is an evolutionary perspective useful? Why or why not?

## Submission details

- Submit your write-up by **`{r} ex_evo_due`** via this [Canvas dropbox](`{r} canvas_db`).
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.

