---
title: "Exercise EMO • Measuring emotion"
subtitle: "**Name:**____________________________"
---

```{r}
#| echo: false
psy_511_vars <- readr::read_csv("data/csv/psy-511-vars.csv", show_col_types = FALSE)
ex_due <- psy_511_vars |>
  dplyr::filter(name == "WK_08_DATE") |>
  dplyr::select(value) |>
  as.character()

canvas_db <- psy_511_vars |>
  dplyr::filter(name == "EX_EMO_CANVAS") |>
  dplyr::select(value) |>
  as.character()
```

## Goals

1. To more deeply understand how emotions are measured.

## Activity

Choose a measure of an emotional or affective state. Write a short, 4-5 pp, essay where you address the following points:

1. How the measure is implemented, e.g., self-report survey, third party observation, physiological measurement, etc.
2. What evidence links measure outcomes to affective state.
3. What evidence links measure outcomes to related measures.
4. What are the principal strengths and weaknesses of this particular measure.
5. How might any weaknesses be mitigated or overcome.

## Submission details

- Submit your write-up by **`{r} ex_due`** via the Canvas [dropbox](`{r} canvas_db`).
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.
