---
title: "Exercise 05 • Neurochemistry"
subtitle: "**Name:**____________________________"
---

## Goals

1. To understand some basic facts about neurotransmitters and their functions in communication.
2. To understand some basic facts about hormones and their functions in communication.
3. To understand how chemical (via neurotransmitters and hormones) and electrical (via action potentials) compare with one another.

## Activity

1. Starting with the arrival of the action potential at the terminal button, describe the main steps that lead to the release of neurotransmitter from the presynaptic terminal.
2. Describe how the binding of neurotransmitter onto an *ionotropic* post-synaptic receptor influences the post-synaptic cell. What is an example of a neurotransmitter that has this effect?
3. Describe how the binding of neurotransmitter onto a *metabotropic* post-synaptic receptor influences the post-synaptic cell. What is an example of a neurotransmitter that has this sort of effect?
4. Describe at least two ways that neurotransmitters released at a synapse are inactivated, with an example for each.
5. Describe some of the key features and roles of glutamate and GABA in the CNS.
6. Describe at least two features that monoamine neurotransmitter systems have in common.
7. Identify a structure in the CNS that controls the endocrine and neural responses to situations that require behavioral activation or increased activity and arousal. Give an example of how this might work in practice.

## Submission details

- Submit your write-up by [**Wednesday, February 26, 2025 at 11:59 pm**]{.orange_due}.
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.

