---
title: "Final project"
---

## Project proposal

Please describe your plan for your final project in a concise, 1-2 page proposal.
Your proposal should describe the form of your project, the topic or topics to be covered, how the project contributes to your scholarly or training goals, and highlight and cite no more than five (5) sources you intend to draw upon.

Please submit the proposal as a Microsoft Word (.docx) formatted document.

The proposal is due on Thursday, March 5, 2026. [Here](https://psu.instructure.com/courses/2441266/assignments/18005251) is the Canvas dropbox.

## Project options

### BBS-style critical review

Write a critical review in the style of a [Behavioral and Brain Sciences (BBS)](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences) commentary.
The target of your review could be a published article in BBS or an article published in another journal.
Examine some existing BBS papers in your areas of interest to see how authors choose to structure their commentaries.
Typically, a BBS commentary is [restricted to 1,000 words](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/information/instructions-contributors), but you have latitude to write up to 2,500 words.

### Popular science piece

Choose a method, a nervous system structure, neurotransmitter or hormone, or a psychological state, and write a "what do we know about" style of piece targeted at the general, science-literate public.
Consult *The New York Times*, *Scientific American*, *The New Scientist*, or *The Economist* for illustrative examples of the structure and style of the piece.
Your piece should be 1,500-2,500 words, and could include illustrations you create, or videos or figures you find (and cite sources for) on the internet.
If you choose a psychological state or behavior, please incorporate a biological perspective in some meaningful way.
If you want to create a website for your content using [Quarto](https://quarto.org) or a similar tool, that is also acceptable. 

### Research proposal

Propose a research study that incorporates one or more biological measures and some well-defined behavior or set of behaviors or psychological states.
Make sure to highlight how biological measures inform and enrich our understanding about the behaviors or psychological states.
Your proposal can be 1,500-2,500 words in length.

### Tutorial

Prepare a complete 20-30 min lecture with slides for a 200-level course on biological or physiological psychology focusing on a topic you might choose to cover were you the instructor of record.

For this project format, you are strongly encouraged to schedule time to present your tutorial to class.

### Exercise

Write an exercise for a future group of PSY 511 students. Your exercise can build upon the existing exercises, replace the content for an existing exercise, or address a topic not covered or covered thoroughly this semester.

For this project, you are strongly encouraged to meet with me in advance.

### A critical dialogue with AI

::: {.callout-important}
## Background
Gilmore has been using Gemini to explore various scientific topics that interest him.
He finds it often to be a useful resource, especially for finding summaries of key ideas and the primary sources for these ideas.
As an example, here is a [dialogue](https://gemini.google.com/share/a2edddc40a00) about monosynaptic stretch reflexes, and [here](https://gemini.google.com/share/f4b71886330c) is one about how Marr's three levels might apply to locomotion.
This exercise gives you an opportunity to explore whether AI is useful to _you_.
:::

Engage in a critical dialogue with an AI service on a topic that you want to know more about. Read the main sources the AI refers to on your topic and provide a report that critiques the AI summary. What does the AI get right, what does it miss or get wrong? How useful is AI for graduate students who are learning about social, cognitive, and affective neuroscience?

You may, but are not required to engage in similar dialogues with more than one AI service. If you do, then please compare and contrast the services.

Make sure to share your dialogue/chat history with the AI(s), and of course, cite the primary source references you used in your critique.

## Tips

- Always put your last name and first name in the file name of all documents you submit. For example, `gilmore-rick-psy-511-2026-final-paper.docx` works fine.
- Submit your paper as a MS Word document using Canvas.
- Include a cover page and title. Make sure to add page numbers.  
- Research proposals and BBS-style reviews should use APA format.
- BBS-style reviews, popular science pieces, and research proposals should include an introduction, body, and conclusion. Depending on the format, you may or may not need to label these sections.
- Unpack and define all acronyms when you first mention them. Define or explain technical terms and concepts.
- Include all end-of-paper citations in a format that is convenient to you and easy to extract from your reference manager.
- Include author-date citations in the text. Footnote-style in-text citations are also acceptable.
- Use double-spacing.
- Run spell-check on your paper before you submit. I also suggest reading your paper out loud as a way to catch run-on sentences, awkward phrasing, and odd word choices.
