---
title: "Exercise AP • Neurophysiology II"
subtitle: "**Name:**____________________________"
---

```{r}
#| echo: false
psy_511_vars <- readr::read_csv("../data/csv/psy-511-vars.csv", show_col_types = FALSE)
ex_due <- psy_511_vars |>
  dplyr::filter(name == "WK_12_DATE") |>
  dplyr::select(value) |>
  as.character()

canvas_db <- psy_511_vars |>
  dplyr::filter(name == "EX_AP_CANVAS") |>
  dplyr::select(value) |>
  as.character()
```

## Goals

1. To understand what change(s) in the resting state of neurons cause the *action potential*.
2. To understand how the action potential results in the release of neurotransmitter from the axon terminal (terminal button).

## Activity

You may work by yourself or with up to two other people for this activity.
If it is easier, you may draw figures and annotate them.

Answer the following questions in no more than a few sentences:

1. What event(s) trigger the *rising phase* of the action potential in the axon initial segment?
2. What event(s) occur at the *peak* of the action potential?
3. What event(s) occur during the *falling phase* of the action potential?
4. Why does the membrane potential overshoot (become more negative than) the typical resting potential?
5. Why can't the neuron fire another action potential during the *absolute* refractory period? What do we need to do to generate an action potential during the *relative* refractory period? 
6. What makes "computing" with wires and action potentials "expensive" for the nervous system?
7. How do psychologists benefit from learning more about these details of neurophysiology?

## Submission details

- Submit your write-up by **`{r} ex_due`** via the Canvas [dropbox](`{r} canvas_db`).
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.
