---
title: "Exercise 02 • Neuroanatomy"
subtitle: "**Name:**____________________________"
---

## Goals

1. To use core neuroanatomical terms in multiple contexts.
2. To practice locating and identifying neuroanatomical structures.
3. To understand what structures are located near other structures.
4. To understand what structures can or cannot be seen from the surface.

## Activity

There will be three stations, one with the brain models, one with brain specimens, and the third with paper atlases.
At each station, do the following:

1. Work through the list below.
2. If you can identify the structure or term, put a check mark.
3. If you are unsure, put a question mark.
4. Structures or terms you *cannot* identify should be left blank.

::: {.callout-note}

If you have time, you might pick one or two of the anatomical structures that you highlighted in [Exercise 01](ex01.qmd) and try to locate them.

If you cannot identify a structure or term in *any* of the stations or atlases, try to find an image on the internet that depicts the structure.
If you 
If this fails, ask Dr. Gilmore for help.

:::

Once you have completed the three stations, you may make a fourth pass through the outline using one (or more) of the electronic atlases:

- Harvard Brain Atlas <http://www.med.harvard.edu/aanlib/cases/caseNA/pb9.htm>
- Allen Brain Atlas
  - [Human female adult (modified Brodmann](http://atlas.brain-map.org/atlas?atlas=265297126#atlas=265297126&plate=112360888&structure=10390&x=40320&y=46976&zoom=-7&resolution=124.49&z=3)
  - [Human female adult (gyral)](http://atlas.brain-map.org/atlas?atlas=138322605#atlas=138322605&plate=112360888&structure=10390&x=40320&y=46976&zoom=-7&resolution=124.49&z=3)
- [3D Brain from Brainfacts.org](https://www.brainfacts.org/3d-brain#intro=false&focus=Brain)
  
Follow the same procedure as before, adding checkmarks, or question marks where appropriate.

## Submission details

- Submit a photocopy or image of your outline by [**Wednesday, January 24, 2024 at 11:59 pm**]{.orange_due}.
- If you found any additional resources that were especially useful to you, please share them.

---

## Directional terms

| Direction          | Model | Specimen | Paper Atlas | Electronic Atlas |
|--------------------|-------------|----------|-------------|------------------|
| Rostral/caudal     |             |          |             |                  |
| Anterior/posterior |             |          |             |                  |
| Medial/lateral     |             |          |             |                  |
| Dorsal/ventral     |             |          |             |                  |
| Superior/inferior  |             |          |             |                  |


## Planes of Section

| Plane                      | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------|--------------|
| [Sagittal](https://en.wikipedia.org/wiki/Sagittal_plane)                   |             |          |       | |
| [Coronal/frontal](https://en.wikipedia.org/wiki/Coronal_plane) |             |          |       | |
| [Axial/horizontal/transverse](https://en.wikipedia.org/wiki/Transverse_plane)           |             |          |       | |

## Brain Structure

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------|--------------|
| [Forebrain](https://en.wikipedia.org/wiki/Prosencephalon)                  |             |          |       | |
| [Midbrain](https://en.wikipedia.org/wiki/Midbrain)                   |             |          |       | |
| [Hindbrain](https://en.wikipedia.org/wiki/Rhombencephalon)                  |             |          |       | |

## Surface of Cerebral Cortex

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------|--------------|
| [Central sulcus](https://en.wikipedia.org/wiki/Central_sulcus)             |             |          |       | |
| [Lateral sulcus/fissure](https://en.wikipedia.org/wiki/Lateral_sulcus)     |             |          |       | |
| [Longitudinal fissure](https://en.wikipedia.org/wiki/Medial_longitudinal_fissure)       |             |          |       | |
| [Cerebral hemispheres](https://en.wikipedia.org/wiki/Cerebral_hemisphere)       |             |          |       | |
| [Parietal lobe](https://en.wikipedia.org/wiki/Parietal_lobe)              |             |          |       | |
| [Frontal lobe](https://en.wikipedia.org/wiki/Frontal_lobe)               |             |          |       | |
| [Insular cortex](https://en.wikipedia.org/wiki/Insular_cortex)             |             |          |       | |
| [Temporal lobe](https://en.wikipedia.org/wiki/Temporal_lobe)              |             |          |       | |
| [Occipital lobe](https://en.wikipedia.org/wiki/Occipital_lobe)             |             |          |       | |
| [Precentral gyrus](https://en.wikipedia.org/wiki/Precentral_gyrus)           |             |          |       | |
| [Postcentral gyrus](https://en.wikipedia.org/wiki/Postcentral_gyrus)          |             |          |       | |
| [Superior temporal gyrus](https://en.wikipedia.org/wiki/Superior_temporal_gyrus)    |             |          |       | |

## Fiber tracts

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------------|------------------|
| [Corpus callosum](https://en.wikipedia.org/wiki/Corpus_callosum)            |             |          |       | |
| [Anterior commissure](https://en.wikipedia.org/wiki/Anterior_commissure)        |             |          |       | |
| [Posterior commissure](https://en.wikipedia.org/wiki/Posterior_commissure)       |             |          |       | |
| [Olfactory nerve, Ist](https://en.wikipedia.org/wiki/Olfactory_nerve)       |             |          |       | |
| [Optic nerve/tract, IInd](https://en.wikipedia.org/wiki/Optic_nerve)    |             |          |       | |
| [Optic chiasm](https://en.wikipedia.org/wiki/Optic_chiasm)               |             |          |       | |
| [Fornix](https://en.wikipedia.org/wiki/Fornix_\(neuroanatomy)                     |             |          |       | |

## Subcortical structures

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------------|------------------|
| [Caudate nucleus](https://en.wikipedia.org/wiki/Caudate_nucleus)            |             |          |       | |
| [Putamen](https://en.wikipedia.org/wiki/Putamen)                    |             |          |       | |
| [Globus Pallidus](https://en.wikipedia.org/wiki/Globus_pallidus)            |             |          |       | |
| [Thalamus](https://en.wikipedia.org/wiki/Thalamus)                   |             |          |       | |
| [Hypothalamus](https://en.wikipedia.org/wiki/Hypothalamus)               |             |          |       | |
| [Pituitary gland](https://en.wikipedia.org/wiki/Pituitary_gland)            |             |          |       | |
| [Hippocampus](https://en.wikipedia.org/wiki/Hippocampus)                |             |          |       | |
| [Amygdala](https://en.wikipedia.org/wiki/Amygdala)                   |             |          |       | |

## Midbrain

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas | 
|----------------------------|-------------|----------|-------------|------------------|
| [Tectum](https://en.wikipedia.org/wiki/Midbrain_tectum)                     |             |          |       | |
| [Superior colliculus](https://en.wikipedia.org/wiki/Superior_colliculus)        |             |          |       | |
| [Inferior colliculus](https://en.wikipedia.org/wiki/Inferior_colliculus)        |             |          |       | |
| [Tegmentum](https://en.wikipedia.org/wiki/Tegmentum)                  |             |          |       | |
| [Substantia nigra](https://en.wikipedia.org/wiki/Substantia_nigra)           |             |          |       | |
| [Ventral tegmental area](https://en.wikipedia.org/wiki/Ventral_tegmental_area)     |             |          |       | |
| [Locus coeruleus](https://en.wikipedia.org/wiki/Locus_coeruleus)            |             |          |       | |

## Hindbrain

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------------|------------------|
| [Cerebellum](https://en.wikipedia.org/wiki/Cerebellum)                 |             |          |       | | 
| [Pons](https://en.wikipedia.org/wiki/Pons)                       |             |          |       | |
| [Medulla Oblongata](https://en.wikipedia.org/wiki/Medulla_oblongata)          |             |          |       | |
| [Spinal cord](https://en.wikipedia.org/wiki/Spinal_cord)                |             |          |       | |

## Ventricles

| Structure                  | Model | Specimen | Paper Atlas | Electronic Atlas |
|----------------------------|-------------|----------|-------------|------------------|
| [Lateral ventricles](https://en.wikipedia.org/wiki/Lateral_ventricles)         |             |          |       | |
| [3rd ventricle](https://en.wikipedia.org/wiki/Third_ventricle)              |             |          |       | |
| [Cerebral aqueduct](https://en.wikipedia.org/wiki/Cerebral_aqueduct)          |             |          |       | |
| [4th ventricle](https://en.wikipedia.org/wiki/Fourth_ventricle)              |             |          |       | |         
