---
title: "Exercise 03 • Neurophysiology I"
subtitle: "**Name:**____________________________"
---

## Goals

1. To understand some basic facts about neurons and glia.
2. To understand the ionic components and balance of forces that give rise to the *resting potential*.

## Activity

You may work by yourself or with up to two other people for this activity.

Answer the following questions in no more than a few sentences:

1. Describe at least two ways that neurons differ from other cells in the body.
2. What are the two main types of myelin-producing glial cells, and where in the body are they found?

Draw and annotate figure(s) to answer the following questions:

Make sure to write a sentence or two to explain what's going on in your figures.

3. Draw a figure that shows the two principal ions that contribute to the neuron's resting potential, and where (inside or outside the neuron) they are most heavily concentrated.
4. Annotate your figure to show the direction of ion flow along each ion's concentration gradient^[Remember that ions flow *down* the concentration gradient, from regions of high concentration to regions of lower concentration].
5. Annotate your figure to show the direction of ion movement caused by the $Na^+/K^+$ (sodium/potassium) ATPase (pump). 
6. Annotate your figure to show what spatial pattern of *electrical* charges (positive/negative voltage; inside the cell/outside the cell) would tend to keep the potassium ($K^+$) ions where they are most highly concentrated when the neuron is at rest. Explain your reasoning.
7. Annotate your figure to show what this *same* pattern of electrical charges would do to sodium ($Na^+$) ions.

Answer the following questions in no more than a few sentences:

8. What change(s) in the neuron could cause potassium ($K^+$) ions to move? Which direction would the ions move under these circumstances?
9. What change(s) in the neuron could cause sodium ($Na^+$) ions to move? Which direction would the ions move under these circumstances?
10. $Na^+/K^+$ (sodium/potassium) ATPase (pump) uses metabolic energy to function. It essentially keeps working constantly. What would happen to the neuron if this process was disrupted somehow?

## Submission details

- Submit your write-up by [**Wednesday, February 12, 2025 at 11:59 pm**]{.orange_due}.
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.
