---
title: "Exercise 07 • Evolution"
subtitle: "**Name:**____________________________"
---

## Goals

1. To practice thinking and reasoning critically about how evolutionary perspectives can inform understanding about psychological phenomena.

## Activity

Answer the following questions in a few short sentences:

1. What feature(s) of the human brain are similar to closely related animals (e.g., mammals and especially primates)?
2. What feature(s) of the human brain distinguish it from these closely related animals?
3. Why is it especially hard to tie changes in human brain structure to particular human psychological characteristics?

Answer the following question in a paragraph or two:

4. Consider a psychological domain that interests you, is an evolutionary perspective useful? Why or why not?

## Submission details

- Submit your write-up by [**Wednesday, March 19, 2025 at 11:59 pm**]{.orange_due}.
- If you work with other people, please indicate the name(s) of your co-authors in your document. You need not include them in the document file name, however.
- If you found any resources that were especially useful to you in answering these questions, please cite them.

